apiVersion: v1
kind: Namespace
metadata:
  name: source
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: source
spec:
  clusterSpec:
    image:
      tag: v26.1.1
    nodeSelector:
      node-pool: redpanda
    statefulset:
      replicas: 3
    storage:
      persistentVolume:
        storageClass: csi-driver-lvm-striped-xfs
        size: 1700Gi  # 1.73 TiB VG (nvme0n1 on r8gd.8xlarge) → ~1771 GiB available
      tiered:
        config:
          cloud_storage_enabled: false
    listeners:
      kafka:
        external:
          default:
            enabled: true
            advertisedPorts:
              - 31092
    external:
      addresses:
        - 10.239.0.79
        - 10.239.2.202
        - 10.239.1.27
    tls:
      enabled: true
    auth:
      sasl:
        enabled: false
