apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omb-control-plane-data
  labels:
    app: omb-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
