{{- if .Values.controlPlane.encryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: omb-control-plane-encryption
  labels:
    app: omb-control-plane
type: Opaque
stringData:
  encryption-key: {{ .Values.controlPlane.encryptionKey | quote }}
{{- end }}
