apiVersion: v1
kind: Service
metadata:
  name: omb-control-plane
  labels:
    app: omb-control-plane
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    {{- toYaml .Values.controlPlane.allowedCIDRs | nindent 4 }}
  selector:
    app: omb-control-plane
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
