apiVersion: v1
kind: Service
metadata:
  name: omb-worker
  labels:
    app: omb-worker
spec:
  clusterIP: None
  selector:
    app: omb-worker
  ports:
    - name: worker
      port: 8080
      targetPort: 8080
      protocol: TCP
