apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omb-worker
  labels:
    app: omb-worker
spec:
  serviceName: omb-worker
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: omb-worker
  template:
    metadata:
      labels:
        app: omb-worker
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node-pool: worker
      tolerations:
        - key: dedicated
          operator: Equal
          value: benchmark
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: omb-worker
              topologyKey: kubernetes.io/hostname
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: OMB_MODE
              value: worker
          ports:
            - containerPort: 8080
              name: worker
          resources:
            requests:
              cpu: {{ .Values.worker.resources.cpu | quote }}
              memory: {{ .Values.worker.resources.memory | quote }}
            limits:
              memory: {{ .Values.worker.resources.memory | quote }}
