"""Workload library CRUD router — /api/workloads."""
import logging
from typing import Dict, List
from uuid import uuid4

import yaml
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database import get_db
from models import Workload
from schemas import WorkloadCreate, WorkloadOut, WorkloadUpdate

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _auto_description(content: str) -> str | None:
    """Parse YAML workload content and return a brief description string.

    Extracts messageSize, partitionsPerTopic, and producerRate fields if
    present.  Returns None when no relevant fields are found or when the
    content cannot be parsed.
    """
    try:
        data = yaml.safe_load(content)
    except yaml.YAMLError:
        return None
    if not isinstance(data, dict):
        return None

    parts: List[str] = []
    if data.get("messageSize"):
        parts.append(f"{data['messageSize'] // 1024}KB messages")
    if data.get("partitionsPerTopic"):
        parts.append(f"{data['partitionsPerTopic']} partitions")
    if data.get("producerRate"):
        rate = data["producerRate"]
        parts.append(f"{rate:,} msg/s target")

    return ", ".join(parts) if parts else None


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@router.get("", response_model=Dict[str, List[WorkloadOut]])
async def list_workloads(
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Return all workloads split by is_bundled flag.

    Response shape: ``{"bundled": [...], "custom": [...]}``.
    """
    result = await db.execute(select(Workload).order_by(Workload.created_at))
    workloads = result.scalars().all()

    bundled = [w for w in workloads if w.is_bundled]
    custom = [w for w in workloads if not w.is_bundled]

    return {
        "bundled": [WorkloadOut.model_validate(w) for w in bundled],
        "custom": [WorkloadOut.model_validate(w) for w in custom],
    }


@router.post("", response_model=WorkloadOut, status_code=201)
async def create_workload(
    body: WorkloadCreate,
    db: AsyncSession = Depends(get_db),
) -> WorkloadOut:
    """Create a new custom workload.

    If ``cloned_from_id`` is provided the source workload must exist.
    If no description is supplied, one is auto-generated by parsing the YAML
    content.
    """
    # Validate cloned_from_id if provided.
    if body.cloned_from_id is not None:
        result = await db.execute(
            select(Workload).where(Workload.id == body.cloned_from_id)
        )
        source = result.scalar_one_or_none()
        if source is None:
            raise HTTPException(
                status_code=404,
                detail=f"Source workload '{body.cloned_from_id}' not found.",
            )

    description = body.description
    if not description:
        description = _auto_description(body.content)

    workload = Workload(
        id=str(uuid4()),
        name=body.name,
        description=description,
        content=body.content,
        is_bundled=False,
        cloned_from_id=body.cloned_from_id,
    )
    db.add(workload)
    try:
        await db.commit()
    except Exception:
        await db.rollback()
        raise

    return WorkloadOut.model_validate(workload)


@router.put("/{workload_id}", response_model=WorkloadOut)
async def update_workload(
    workload_id: str,
    body: WorkloadUpdate,
    db: AsyncSession = Depends(get_db),
) -> WorkloadOut:
    """Update a custom workload.

    Returns 404 if the workload does not exist.
    Returns 403 if the workload is bundled (read-only).
    """
    result = await db.execute(
        select(Workload).where(Workload.id == workload_id)
    )
    workload = result.scalar_one_or_none()

    if workload is None:
        raise HTTPException(status_code=404, detail="Workload not found.")

    if workload.is_bundled:
        raise HTTPException(
            status_code=403,
            detail="Bundled workloads are read-only and cannot be edited.",
        )

    workload.name = body.name
    workload.content = body.content
    # Allow explicit None to clear the description; fall back to auto-generate
    # only when the field is absent would require a PATCH — here PUT always
    # overwrites so we respect whatever the caller sends (including None).
    workload.description = body.description

    try:
        await db.commit()
    except Exception:
        await db.rollback()
        raise

    return WorkloadOut.model_validate(workload)


@router.delete("/{workload_id}", status_code=204)
async def delete_workload(
    workload_id: str,
    db: AsyncSession = Depends(get_db),
) -> None:
    """Delete a custom workload.

    Returns 404 if the workload does not exist.
    Returns 403 if the workload is bundled (read-only).
    """
    result = await db.execute(
        select(Workload).where(Workload.id == workload_id)
    )
    workload = result.scalar_one_or_none()

    if workload is None:
        raise HTTPException(status_code=404, detail="Workload not found.")

    if workload.is_bundled:
        raise HTTPException(
            status_code=403,
            detail="Bundled workloads are read-only and cannot be deleted.",
        )

    await db.delete(workload)
    try:
        await db.commit()
    except Exception:
        await db.rollback()
        raise
